apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # UPDATE THIS: Replace with your actual MongoDB Atlas connection string
  MONGO_URI: "mongodb+srv://nextgenerdev_db_user:1fRKAxDNOcPTNono@travelmemory.tkwbrda.mongodb.net/?appName=travelmemory"

  # UPDATE THESE: Replace with your actual secrets
  JWT_SECRET: "testingJwtKey"
  AWS_ACCESS_KEY_ID: "ASIAZCZ2ZCAEA3F2TYMS"
  AWS_SECRET_ACCESS_KEY: "Oj2t4lrGXEhSPWQLEy2NKlSx54CQm4HE+KDGfdL7"
